// Replace with your request types
export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_RECEIVE = 'GET_DATA_RECEIVE';
export const GET_DUMMY_DATA_REQUEST = 'GET_DUMMY_DATA_REQUEST';
export const GET_DUMMY_DATA_RECEIVE = 'GET_DUMMY_DATA_RECEIVE'
export const SET_DUMMY_DATA = 'SET_DUMMY_DATA'
export const SET_SELECTED_GENRE = 'SET_SELECTED_GENRE'
export const SET_SUBGENRES_OF_GENRE = 'SET_SUBGENRES_OF_GENRE'
